/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles_De_Control;

import Admin.*;
import Arreglos.Arreglo_admin;
import Arreglos.Arreglo_user;
import Login.Login_;
import Users.User_;
import dao.clases.administradorCAD;
import dao.clases.usuarioCAD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class PanelControl_Admins extends javax.swing.JFrame {
    Admin_ aux = Administracion.cuenta;
    Arreglo_admin obj = new Arreglo_admin();
    Arreglo_user obj_2 = new Arreglo_user();
    administradorCAD cadAdministrador = new administradorCAD();
    usuarioCAD cadUsuario = new usuarioCAD();
    public PanelControl_Admins() {
        initComponents();
        jButton3.setEnabled(false);
        jTextField1.requestFocus();
        jTextField3.setText(aux.getNombre()+" "+aux.getApellido());
        jTextField7.setText(aux.getUsuario());
        jTextField4.setText(aux.getEmail());
        jPasswordField1.setText(aux.getContraseña());
        jTextField5.setText(aux.getNombre());
        jTextField2.setText(aux.getApellido());
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton7.setEnabled(false);
        desabilitar();
    }
    public void desabilitar(){
        jTextField9.setEditable(false);
        jTextField12.setEditable(false);
        jTextField13.setEditable(false);
        jTextField15.setEditable(false);
    }
    public void habilitar(){
        jTextField9.setEditable(true);
        jTextField12.setEditable(true);
        jTextField13.setEditable(true);
        jTextField15.setEditable(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField17 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de control para Administradores");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese correo electronico"));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 178, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_panel/label_registro_usuario_admin.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 50));

        jTextField10.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese nombre"));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 178, 50));

        jTextField11.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese Apellido"));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 50));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 240, 50));

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 100, 30));

        jButton3.setText("Nuevo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 90, 30));

        jPasswordField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese de nuevo la contraseña"));
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, 50));

        jPasswordField3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese contraseña"));
        jPanel1.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, 50));

        jTextField8.setEditable(false);
        jTextField8.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario Generado"));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 200, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_panel/fondo_panel_admin.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 402));

        jTabbedPane1.addTab("Registrar Usuarios o Administradores", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField9.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 230, 50));

        jTextField12.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 230, 50));

        jTextField13.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, 50));

        jTextField16.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, 50));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de cuenta"));
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, 50));

        jButton4.setText("Dar acceso");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 130, 30));

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 130, 30));

        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 130, 30));

        jButton7.setText("Nuevo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 130, 30));

        jTextField15.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_panel/fondo_panel_admin.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 795, 402));

        jTabbedPane1.addTab("Modificar Usuarios o Administradores", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField17.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jPanel3.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 190, 50));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Cuenta"));
        jPanel3.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 190, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de cuenta a Eliminar"));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 280, 200));

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 100, 40));

        jButton9.setText("Elimnar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 100, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_panel/eliminar_fondo_cuentas.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 220, 180));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_panel/fondo_panel_admin.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 795, 402));

        jTabbedPane1.addTab("Eliminar Usuarios o Administradores", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_panel/Cerrar_sesion.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 349, 100, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setBorder(null);
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 130, 30));

        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 410, 50));

        jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 410, 50));

        jTextField7.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 410, 50));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        jPanel4.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 150, 410, 50));

        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 410, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_panel/admin_cuenta.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 795, 402));

        jTabbedPane1.addTab("Cuenta", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login_ windows = new Login_();
        windows.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String usuario,email,contraseña,contraseña_2,nombre,apellido,opcion;
       opcion = jComboBox1.getSelectedItem().toString();
       email = jTextField1.getText();
       contraseña = jPasswordField3.getText();
       contraseña_2 = jPasswordField2.getText();
       nombre = jTextField10.getText();
       apellido = jTextField11.getText();
       if(!contraseña.equals(contraseña_2)){
           JOptionPane.showMessageDialog(null,"Las contraseñas no son identicas valide porfavor");
       }else{
          if(opcion.equals("Administrador")){
              Admin_ ad = new Admin_(email, contraseña, nombre, apellido, "");
              cadAdministrador.crear(ad);
              jTextField8.setText(cadAdministrador.obtener().get((cadAdministrador.obtener().size()-1)).getUsuario());
              JOptionPane.showMessageDialog(null, "¡Cuenta de Administrador creada con exito!");
              jButton2.setEnabled(false);
              jButton3.setEnabled(true);
          }else if(opcion.equals("Usuario")){
              User_ us = new User_(email, contraseña, nombre, apellido, "");
              cadUsuario.crear(us);
              jTextField8.setText(cadUsuario.obtener().get((cadUsuario.obtener().size()-1)).getUsuario());
              JOptionPane.showMessageDialog(null, "¡Cuenta de Usuario creada con exito!");
              jButton2.setEnabled(false);
              jButton3.setEnabled(true);
          }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jComboBox1.setSelectedIndex(0);
        jTextField1.setText("");
        jPasswordField3.setText("");
        jPasswordField2.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField8.setText("");
        jButton2.setEnabled(true);
        jButton3.setEnabled(false);
        jTextField1.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String user = jTextField16.getText();
        String tipo = jComboBox3.getSelectedItem().toString();
        if(tipo.equals("Administrador")){
            Admin_ bus = cadAdministrador.buscar(user);
            if(bus == null){
                JOptionPane.showMessageDialog(null, "El usuario no existe");
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
                jButton7.setEnabled(false);
            }else{
                jTextField9.setText(bus.getEmail());
                jTextField12.setText(bus.getContraseña());
                jTextField13.setText(bus.getNombre());
                jTextField15.setText(bus.getApellido());
                jButton4.setEnabled(true);
            }
        }else if(tipo.equals("Usuario")){
            User_ us = cadUsuario.buscar(user);
            if(us == null){
                JOptionPane.showMessageDialog(null, "El usuario no existe");
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
                jButton7.setEnabled(false);
            }else{
                jTextField9.setText(us.getEmail());
                jTextField12.setText(us.getContraseña());
                jTextField13.setText(us.getNombre());
                jTextField15.setText(us.getApellido());
                jButton4.setEnabled(true);
            }
            
        
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        habilitar();
        jButton5.setEnabled(true);
        jButton7.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTextField9.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jComboBox3.setSelectedIndex(0);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton7.setEnabled(false);
        jTextField16.requestFocus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String user = jTextField16.getText();
        String correo = jTextField9.getText();
        String contraseña = jTextField12.getText();
        String nombre = jTextField13.getText();
        String apellido = jTextField15.getText();
        String tipo = jComboBox3.getSelectedItem().toString();
        if(tipo.equals("Administrador")){
            Admin_ bus = cadAdministrador.buscar(user);
            if(bus == null){
                JOptionPane.showMessageDialog(null, "El usuario no existe");
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
                jButton7.setEnabled(false);
            }else{
                bus.setApellido(apellido);
                bus.setContraseña(contraseña);
                bus.setEmail(correo);
                bus.setNombre(nombre);
                cadAdministrador.actualizar(bus);
                JOptionPane.showMessageDialog(null, "Modificacion exitosa");
            }
        }else if(tipo.equals("Usuario")){
            User_ us = cadUsuario.buscar(user);
            if(us == null){
                JOptionPane.showMessageDialog(null, "El usuario no existe");
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
                jButton7.setEnabled(false);
            }else{
                us.setApellido(apellido);
                us.setContraseña(contraseña);
                us.setEmail(tipo);
                us.setNombre(nombre);
                cadUsuario.actualizar(us);
                JOptionPane.showMessageDialog(null, "Modificacion exitosa");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        String tipo = jComboBox4.getSelectedItem().toString();
        String user = jTextField17.getText();
        if(tipo.equals("Administrador")){
            Admin_ ad = cadAdministrador.buscar(user);
            if(ad == null){
                JOptionPane.showMessageDialog(null, "Cuenta de administrador inexistente");
            }else{
                jTextArea1.setText(""+ad.getNombre()+"\n"+ad.getApellido()+"\n"+ad.getEmail()+"\n"+ad.getContraseña());
            }
        }else if(tipo.equals("Usuario")){
            User_ us = cadUsuario.buscar(user);
            if(us == null){
                JOptionPane.showMessageDialog(null, "Cuenta de Usuario inexistente");
            }else{
                jTextArea1.setText(""+us.getNombre()+"\n"+us.getApellido()+"\n"+us.getEmail()+"\n"+us.getContraseña());
            }
        }else{
            JOptionPane.showMessageDialog(null, "ERROR REVISA EL COMBO BOX");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String tipo = jComboBox4.getSelectedItem().toString();
        String user = jTextField17.getText();
        if(tipo.equals("Administrador")){
            Admin_ ad = cadAdministrador.buscar(user);
            if(ad == null){
                JOptionPane.showMessageDialog(null, "Cuenta de administrador inexistente");
            }else{
                cadAdministrador.borrar(ad.getUsuario());
                JOptionPane.showMessageDialog(null, "Administrador eliminado correctamente");
            }
        }else if(tipo.equals("Usuario")){
            User_ us = cadUsuario.buscar(user);
            if(us == null){
                JOptionPane.showMessageDialog(null, "Cuenta de Usuario inexistente");
            }else{
                cadUsuario.borrar(us.getUsuario());
                JOptionPane.showMessageDialog(null, "Usuario eliminado correctamente");
            }
        }else{
            JOptionPane.showMessageDialog(null, "ERROR REVISA EL COMBO BOX");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelControl_Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelControl_Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelControl_Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelControl_Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelControl_Admins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
